# Generated by Django 6.1 on 2026-08-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact ',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['-email'],
            },
        ),
    ]
