# Generated by Django 6.1 on 2026-08-21 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0005_alter_blacklistip_id_alter_blacklistuseragent_id_and_more'),
        ('news', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='newness',
            name='hitcount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='hitcount.hitcount'),
        ),
    ]
