# Generated by Django 6.1 on 2026-08-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newness_hitcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newness',
            name='hitcount',
        ),
    ]
