# Generated by Django 6.1 on 2026-08-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newness_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='newness',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
