# Generated by Django 6.1 on 2026-08-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newness_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newness',
            name='view_count',
        ),
    ]
