# Generated by Django 6.1 on 2026-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_newness_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='newness',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newness',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
