# Generated by Django 6.1 on 2026-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newness_id_alter_newness_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newness',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newness',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newness',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newness',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newness',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newness',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
