# Generated by Django 6.1 on 2026-08-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment'),
        ('news', '0008_category_title_en_category_title_ru_and_more'),
    ]

    operations = [
    ]
