# Generated by Django 6.1 on 2026-08-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_merge_20260826_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
